-- CreateTable
CREATE TABLE "physical_tests" (
    "id" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "name" TEXT NOT NULL,
    "gender" TEXT NOT NULL,
    "birthdate" TIMESTAMP(3) NOT NULL,
    "height" DECIMAL(9,2) NOT NULL,
    "weight" DECIMAL(9,2) NOT NULL,
    "flexibility_first_attempt" DECIMAL(9,2),
    "flexibility_second_attempt" DECIMAL(9,2),
    "flexibility_evaluator" TEXT,
    "wingspan" DECIMAL(9,2),
    "wingspan_evaluator" TEXT,
    "strength_resistance" INTEGER,
    "strength_resistance_evaluator" TEXT,
    "muscular_endurance_first_attempt" INTEGER,
    "muscular_endurance_second_attempt" INTEGER,
    "muscular_endurance_evaluator" TEXT,
    "lower_limb_strength_first_attempt" DECIMAL(9,2),
    "lower_limb_strength_second_attempt" DECIMAL(9,2),
    "lower_limb_strength_evaluator" TEXT,
    "upper_limb_strength_first_attempt" DECIMAL(9,2),
    "upper_limb_strength_second_attempt" DECIMAL(9,2),
    "upper_limb_strength_evaluator" TEXT,
    "agility_first_attempt" DECIMAL(9,2),
    "agility_second_attempt" DECIMAL(9,2),
    "agility_evaluator" TEXT,
    "general_resistance" DECIMAL(9,2),
    "general_resistance_evaluator" TEXT,
    "speed" DECIMAL(9,2),
    "speed_evaluator" TEXT,

    CONSTRAINT "physical_tests_pkey" PRIMARY KEY ("id")
);
